param([string]$doInstall = "true")

function Exit-If-LastExitCode-Not-0
{
   if ($LastExitCode -ne 0)
   {
      Write-Host "[QuickVsix.ps1] ExitCode: $LastExitCode"
      exit $LastExitCode
   }
}

Write-Host "[QuickVsix.ps1] Running nuget.exe restore"
nuget.exe restore
Exit-If-LastExitCode-Not-0

Write-Host "[QuickVsix.ps1] Running dotnet.exe build"
dotnet.exe build QuickVsix.sln --configuration Release
Exit-If-LastExitCode-Not-0

Write-Host "[QuickVsix.ps1] Running dotnet.exe test"
dotnet.exe test /p:AltCover=true /p:AltCoverReport="AltCoverCodeCoverageResults_QuickVsixTests.xml" /p:AltCoverAssemblyFilter="AltCover.Monitor|DocoptPlus|FakeItEasy|NUnit3.TestAdapter" /p:AltCoverAttributeFilter="ExcludeFromCodeCoverage" /p:AltCoverTypeFilter="System.Runtime.CompilerServices|AutoGeneratedProgram"
Exit-If-LastExitCode-Not-0

Write-Host "[QuickVsix.ps1] Running OpenCoverToCoberturaConverter.exe"
OpenCoverToCoberturaConverter.exe -input:"QuickVsixTests\AltCoverCodeCoverageResults_QuickVsixTests.xml" -output:"QuickVsixTests\CoberturaCodeCoverageResults_QuickVsixTests.xml" -sources:.
Exit-If-LastExitCode-Not-0

Write-Host "[QuickVsix.ps1] Running ReportGenerator.exe"
ReportGenerator.exe -reports:"QuickVsixTests\AltCoverCodeCoverageResults_QuickVsixTests.xml" -targetdir:"QuickVsixTests\ReportGenerator_QuickVsixTests" -reporttypes:HtmlInline
Exit-If-LastExitCode-Not-0

if ($doInstall -eq "true")
{
   Remove-Item -Recurse -Verbose "C:\bin\QuickVsix" -ErrorAction Ignore | Out-Null
   mkdir "C:\bin\QuickVsix" -ErrorAction Ignore | Out-Null
   Copy-Item -Verbose "QuickVsix\bin\Release\net7.0\*" "C:\bin\QuickVsix\"
}

Write-Host "[QuickVsix.ps1] ExitCode: 0"
